### ISSUE TITLE
outDirを使えない

### ISSUE THREAD

**Issue by tecsoc** [mahaker/esbuild-gas-plugin#18]
```ts
entryPoints: ['src/*.ts'],
outdir: 'dist'
```
のようにして、src配下のtsファイルをdistに出力したいのですが
`RROR: [plugin: gas-plugin] "outfile" is required. Note that "write: false" is not available.`
というエラーが発生してしまいます。

outfileではなくoutDirも使えるようになると嬉しいです

**Comment by mahaker** [comment]
This plugin does not support the `outdir` option.
The reason is that it is necessary to limit the output of GAS function definitions (created by [gas-entry-generator](https://github.com/fossamagna/gas-entry-generator)) because it is necessary to limit the output to a single file.

Could you tell me why the `outdir` option is necessary (especially in GAS development)?
Also, is it not possible to set `bundle: true`?

**Comment by tecsoc** [comment]
> The reason is that it is necessary to limit the output of GAS function definitions (created by [gas-entry-generator]
(https://github.com/fossamagna/gas-entry-generator)) because it is necessary to limit the output to a single file.

I'm still trying to fully understand this.
I am currently able to split js files into multiple files and develop in GAS. I would like to typescript this.
I don't want to change the format as much as possible and I want to keep the file structure.
Then, outDir was needed.

> ould you tell me why the outdir option is necessary (especially in GAS development)?

Also, is it not possible to set bundle: true?
I thought that specifying `bundle: false `would do what I wanted, but
As long as I am using wildcards to specify entry points, it seems that outDir is required.
I got a this error.
`error: Must use "outdir" when there are multiple input files`

**Comment by mahaker** [comment]
Thanks for the reply.

In your project, are you developing with multiple files without using require?
If you don't mind, could you create a mock project on Github with the same structure?
I am very interested to see how you develop.

We can't use the module system like require or import/export in GAS.
You have to define a function and call it from another file.
Since this would not allow us to take advantage of TypeScript types, I would recommend rewriting it in a modular format using import/export and then setting `bundle: true` and `outfile`.

**Comment by tecsoc** [comment]
I had published its repository on GitHub.
[Here](https://github.com/tecsoc/weather-forecast-notify-gas)

If using `bundle: true` and `outfile`, multiple files are combined into one, which makes it less readable when debugging, right?
We're hoping to avoid that.

**Comment by mahaker** [comment]
This plugin is originally intended to allow npm modules to be used with GAS.
The module system are not available in GAS, it is necessary to bundle (combine files into one) including npm modules.
You have to set the `outfile` option for that.

**Comment by tecsoc** [comment]
I see.
So, it's a little different what I'm wanting for?

**Comment by mahaker** [comment]
Perhaps it is.
For TypeScript projects that do not use require or import/export, I think you can just use tsc or clasp to transpile.

**Comment by tecsoc** [comment]
Thank you for your advice
I will close this PR.
